name: drugdesign_310
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.2.0
  - alabaster=1.0.0
  - annotated-types=0.7.0
  - appdirs=1.4.4
  - astunparse=1.6.3
  - babel=2.17.0
  - boost-cpp=1.84.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.1.31
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - dgllife=0.3.2
  - docker-pycreds=0.4.0
  - docutils=0.21.2
  - eval_type_backport=0.2.2
  - expat=2.6.4
  - filelock=3.13.1
  - flatbuffers=24.3.25
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - future=1.0.0
  - gast=0.6.0
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-pasta=0.2.0
  - greenlet=3.1.1
  - grpcio=1.62.2
  - h5py=3.13.0
  - hdf5=1.14.3
  - hyperopt=0.2.7
  - icu=73.2
  - idna=3.7
  - imagesize=1.4.1
  - importlib-metadata=8.6.1
  - jinja2=3.1.6
  - joblib=1.4.2
  - keras=3.9.0
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lapack=3.9.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-devel=1.84.0
  - libboost-headers=1.84.0
  - libboost-python=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=20.1.1
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.80.2
  - libgrpc=1.62.2
  - libiconv=1.18
  - libintl=0.23.1
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.29
  - libpng=1.6.43
  - libpq=16.8
  - libprotobuf=4.25.3
  - librdkit=2024.03.6
  - libre2-11=2023.09.01
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.5.0
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=20.1.1
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - mdurl=0.1.2
  - ml_dtypes=0.3.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - namex=0.0.8
  - ncurses=6.4
  - networkx=3.4.2
  - numpy=1.26.4
  - openblas=0.3.29
  - openjpeg=2.5.2
  - openssl=3.4.1
  - opt_einsum=3.4.0
  - optree=0.14.1
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.43
  - pillow=10.3.0
  - pip=25.0
  - pixman=0.44.2
  - platformdirs=4.3.7
  - protobuf=4.25.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - py4j=0.10.9.9
  - pycairo=1.27.0
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.2.10
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - rdkit=2024.03.6
  - re2=2023.09.01
  - readline=8.2
  - reportlab=4.3.1
  - requests=2.32.3
  - rich=13.9.4
  - rlpycairo=0.2.0
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sentry-sdk=2.24.1
  - setproctitle=1.3.5
  - setuptools=75.8.0
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - snowballstemmer=2.2.0
  - sphinx=8.1.3
  - sphinx_rtd_theme=3.0.1
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlalchemy=2.0.40
  - sqlite=3.45.3
  - swig=4.2.1
  - sympy=1.13.3
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - tensorflow=2.16.1
  - tensorflow-base=2.16.1
  - tensorflow-estimator=2.16.1
  - termcolor=2.5.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tomli=2.2.1
  - torchdata=0.7.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - typing=3.10.0.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - vina=1.2.6
  - wandb=0.19.8
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - black==25.1.0
      - dgl==2.1.0
      - fsspec==2025.3.0
      - mypy-extensions==1.0.0
      - pathspec==0.12.1
